Fixed checking env parameters for mongo
knowankit/trello-clone pull request #144
Opened 2022-06-18 13:11 UTC by StounhandJ

When the application is launched in developer mode, unnecessary environment parameters that are not used are checked.

2022-08-03 10:31 UTC, knowankit requested changes
@StounhandJ Can you check it again?

2022-08-03 10:31 UTC, knowankit commented on util/mongodb.js
> +if (NODE_ENV !== 'development' && !MONGODB_URI) {
```suggestion
if (NODE_ENV === 'development' && !MONGODB_URI) {
```
I think we need to raise this only on development. Isn't it?

2022-08-03 10:31 UTC, knowankit commented on util/mongodb.js
> +if (NODE_ENV !== 'development' && !LOCAL_MONGODB) {
```suggestion
if (NODE_ENV === 'development' && !LOCAL_MONGODB) {
```

2022-08-03 15:45 UTC, StounhandJ commented
At the moment when I corrected these errors, my decision was quite correct. It allowed the data to be processed correctly and errors to be displayed. It is necessary to use the sign "!==". But if you think otherwise, you can merge the current version as well.

2022-11-09 03:18 UTC, goswamianshuman commented
### for the following problem please add the following changes to the .env.local file at localhost: 

**Solution :**
please add the following to .env.local file

```
MONGODB_URI=mongodb://localhost:27017/trello
MONGODB_DB=example  
```
you can use any db in replacement of example

2025-10-14 13:55 UTC, closed without merging